name: Deploy Astro to GitHub Pages with Bun

on:
  # Trigger the workflow on push to the `main` branch or manual execution
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out your repository using git
        uses: actions/checkout@v2

      - name: Build Astro with Bun
        run:
          bunx --bun astro build
          # Ex: bun build (for most recent Bun versions)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist # Assuming the build output is in the `dist` directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          content-path: ./dist # Same as the uploaded artifact path
          force-orphan: true # Ensure a clean deployment

